import { Bounty, UserProfile } from '../types';

export const mockBounties: Bounty[] = [
  {
    id: '1',
    claim: 'Tesla announced a fully autonomous vehicle fleet for 2025',
    description: 'A viral post claims Tesla will deploy a fully autonomous robotaxi fleet operating without any human oversight by Q1 2025.',
    stakeAmount: 5.0,
    status: 'resolved',
    submitter: '7xKp...4mNq',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 5,
    category: 'Technology',
    totalSubmissions: 14,
    tags: ['Tesla', 'Autonomous Vehicles', 'Technology'],
    evidence: [
      {
        id: 'e1',
        submitter: '3aRt...9pLw',
        content: 'Tesla has not released any official statement confirming a fully autonomous fleet for 2025. The FSD system still requires driver attention.',
        url: 'https://tesla.com/autopilot',
        timestamp: Date.now() - 1000 * 60 * 60 * 24 * 8,
        upvotes: 23,
      },
      {
        id: 'e2',
        submitter: '9cMn...2kXv',
        content: 'Regulatory approvals for fully driverless vehicles in most US states have not been granted to Tesla as of late 2024.',
        timestamp: Date.now() - 1000 * 60 * 60 * 24 * 6,
        upvotes: 17,
      },
    ],
    verdict: {
      factChecker: '5bJk...8dRs',
      result: 'false',
      explanation: 'No official Tesla announcement supports this claim. FSD v12 exists but still requires human supervision. Regulatory approvals are pending.',
      timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2,
      confidence: 93,
    },
  },
  {
    id: '2',
    claim: 'WHO declared a new global health emergency related to a respiratory virus in January 2025',
    description: 'Multiple news sources are reporting that the World Health Organization declared a new PHEIC in January 2025 for a novel respiratory illness spreading across Southeast Asia.',
    stakeAmount: 8.5,
    status: 'in-review',
    submitter: '2mBv...6nKp',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 12,
    category: 'Health',
    totalSubmissions: 7,
    tags: ['WHO', 'Health Emergency', 'Pandemic'],
    evidence: [
      {
        id: 'e3',
        submitter: '1aXz...7cPq',
        content: 'WHO.int shows no PHEIC declaration in January 2025 on their official emergency declarations page.',
        url: 'https://who.int/emergencies',
        timestamp: Date.now() - 1000 * 60 * 60 * 24 * 1,
        upvotes: 9,
      },
    ],
  },
  {
    id: '3',
    claim: 'Bitcoin will reach $200,000 by end of 2025 according to MicroStrategy',
    description: 'Michael Saylor of MicroStrategy allegedly made a prediction that Bitcoin will reach $200K by Q4 2025 in a recent interview.',
    stakeAmount: 3.2,
    status: 'open',
    submitter: '8pLx...1mNb',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 20,
    category: 'Finance',
    totalSubmissions: 2,
    tags: ['Bitcoin', 'MicroStrategy', 'Crypto', 'Finance'],
    evidence: [],
  },
  {
    id: '4',
    claim: 'India passed a new digital privacy law banning end-to-end encryption',
    description: 'Reports claim India\'s parliament passed legislation that requires tech companies to provide government backdoor access, effectively banning E2E encryption.',
    stakeAmount: 6.0,
    status: 'disputed',
    submitter: '4kNm...2wBv',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 8,
    category: 'Policy',
    totalSubmissions: 19,
    tags: ['India', 'Privacy', 'Encryption', 'Digital Law'],
    evidence: [
      {
        id: 'e4',
        submitter: '6dMk...3pQr',
        content: 'The Digital Personal Data Protection Act 2023 discusses data localization but does not explicitly ban E2E encryption.',
        timestamp: Date.now() - 1000 * 60 * 60 * 24 * 5,
        upvotes: 31,
      },
      {
        id: 'e5',
        submitter: '9xRt...5nLw',
        content: 'Some provisions in the proposed amendment could be interpreted as requiring backdoor access. Legal experts disagree on scope.',
        timestamp: Date.now() - 1000 * 60 * 60 * 24 * 4,
        upvotes: 14,
      },
    ],
    verdict: {
      factChecker: '2cBw...7mKp',
      result: 'misleading',
      explanation: 'The law discusses data access requirements but a flat ban on E2E encryption is an overstatement. The situation is legally ambiguous and ongoing.',
      timestamp: Date.now() - 1000 * 60 * 60 * 24 * 1,
      confidence: 71,
    },
  },
  {
    id: '5',
    claim: 'OpenAI released GPT-5 with over 1 trillion parameters in March 2025',
    description: 'Social media posts claim OpenAI quietly released GPT-5 with 1 trillion+ parameters, surpassing all previous language models.',
    stakeAmount: 4.8,
    status: 'open',
    submitter: '5wZq...9vMn',
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 30,
    category: 'Technology',
    totalSubmissions: 0,
    tags: ['OpenAI', 'GPT-5', 'AI', 'Machine Learning'],
    evidence: [],
  },
  {
    id: '6',
    claim: 'NASA confirmed evidence of microbial life on Mars from Perseverance data',
    description: 'A leaked NASA memo allegedly shows Perseverance rover data contains biomarkers consistent with ancient microbial life.',
    stakeAmount: 12.0,
    status: 'open',
    submitter: '3hRk...8bNx',
    createdAt: Date.now() - 1000 * 60 * 60 * 6,
    expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 45,
    category: 'Science',
    totalSubmissions: 1,
    tags: ['NASA', 'Mars', 'Space', 'Astrobiology'],
    evidence: [],
  },
];

export const mockUserProfile: UserProfile = {
  walletAddress: '7xKp3mNq2bVw1pLx9cMn4kRt6dJm8hBv5nQr2wZs',
  username: 'CryptoVerifier',
  reputationScore: 847,
  bountiesSubmitted: 23,
  bountiesResolved: 18,
  totalStaked: 94.5,
  totalEarned: 127.3,
  successRate: 78,
  joinedAt: Date.now() - 1000 * 60 * 60 * 24 * 180,
  badges: [
    {
      id: 'b1',
      name: 'First Verify',
      description: 'Successfully verified your first bounty claim',
      icon: '🏆',
      earnedAt: Date.now() - 1000 * 60 * 60 * 24 * 170,
    },
    {
      id: 'b2',
      name: 'Accuracy Streak',
      description: 'Maintained 80%+ accuracy for 10 consecutive verdicts',
      icon: '🎯',
      earnedAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
    },
    {
      id: 'b3',
      name: 'Whale Staker',
      description: 'Staked over 50 SOL in total across all bounties',
      icon: '🐋',
      earnedAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    },
    {
      id: 'b4',
      name: 'Community Pillar',
      description: 'Contributed evidence accepted by 20+ fact-checkers',
      icon: '🤝',
      earnedAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    },
  ],
};
